import { TradingData } from '@/types/trenches';

export const tradingData: TradingData = {
  justLaunched: [
    {
      token: 'WOOF47',
      name: 'How A Dog Works',
      filename: 'H8U4X...ump',
      percentage: '2.5',
      holders: '4/5',
      rating: 2,
      change: '1.5',
      successRate: 13,
      volume: '80K',
      marketCap: '5K',
      transactions: 14,
      creator: 'Pumpit',
      earnings: 42,
      holdTime: '3d',
    },
    {
      token: 'WOOF47',
      name: 'How A Dog Works',
      filename: 'H8U4X...ump',
      percentage: '2.5',
      holders: '4/5',
      rating: 2,
      change: '1.5',
      successRate: 13,
      volume: '80K',
      marketCap: '5K',
      transactions: 14,
      creator: 'Pumpit',
      hasRun: true,
      earnings: 42,
      holdTime: '3d',
    },
    {
      token: 'WOOF47',
      name: 'How A Dog Works',
      filename: 'H8U4X...ump',
      percentage: '2.5',
      holders: '4/5',
      rating: 2,
      change: '1.5',
      successRate: 13,
      volume: '80K',
      marketCap: '5K',
      transactions: 14,
      creator: 'Pumpit',
      hasRun: true,
      earnings: 42,
      holdTime: '3d',
    },
    {
      token: 'WOOF47',
      name: 'How A Dog Works',
      filename: 'H8U4X...ump',
      timeLeft: '2h 15m',
      percentage: '2.5',
      holders: '4/5',
      rating: 2,
      change: '1.5',
      successRate: 13,
      volume: '80K',
      marketCap: '5K',
      transactions: 14,
      creator: 'Pumpit',
      hasRun: true,
      earnings: 42,
      holdTime: '3d',
    },
    {
      token: 'WOOF47',
      name: 'How A Dog Works',
      filename: 'H8U4X...ump',
      timeLeft: '2h 15m',
      percentage: '2.5',
      holders: '4/5',
      rating: 2,
      change: '1.5',
      successRate: 13,
      volume: '80K',
      marketCap: '5K',
      transactions: 14,
      creator: 'Pumpit',
      hasRun: true,
      earnings: 42,
      holdTime: '3d',
    },
    {
      token: 'WOOF47',
      name: 'How A Dog Works',
      filename: 'H8U4X...ump',
      percentage: '2.5',
      holders: '4/5',
      rating: 2,
      change: '1.5',
      successRate: 13,
      volume: '80K',
      marketCap: '5K',
      transactions: 14,
      creator: 'Pumpit',
      earnings: 42,
      holdTime: '3d',
    },
    {
      token: 'WOOF47',
      name: 'How A Dog Works',
      filename: 'H8U4X...ump',
      percentage: '2.5',
      holders: '4/5',
      rating: 2,
      change: '1.5',
      successRate: 13,
      volume: '80K',
      marketCap: '5K',
      transactions: 14,
      creator: 'Pumpit',
      hasRun: true,
      earnings: 42,
      holdTime: '3d',
    },
    {
      token: 'WOOF47',
      name: 'How A Dog Works',
      filename: 'H8U4X...ump',
      timeLeft: '1h 30m',
      percentage: '2.5',
      holders: '4/5',
      rating: 2,
      change: '1.5',
      successRate: 13,
      volume: '80K',
      marketCap: '5K',
      transactions: 14,
      creator: 'Pumpit',
      earnings: 42,
      holdTime: '3d',
    },
  ],
  active: [
    {
      token: 'WOOF47',
      name: 'How A Dog Works',
      filename: 'H8U4X...ump',
      percentage: '2.5',
      holders: '4/5',
      rating: 2,
      change: '1.5',
      successRate: 13,
      volume: '80K',
      marketCap: '5K',
      transactions: 14,
      creator: 'Pumpit',
      hasRun: true,
      earnings: 42,
      holdTime: '3d',
    },
    {
      token: 'WOOF47',
      name: 'How A Dog Works',
      filename: 'H8U4X...ump',
      percentage: '2.5',
      holders: '4/5',
      rating: 2,
      change: '1.5',
      successRate: 13,
      volume: '80K',
      marketCap: '5K',
      transactions: 14,
      creator: 'Pumpit',
      hasRun: true,
      earnings: 42,
      holdTime: '3d',
    },
    {
      token: 'WOOF47',
      name: 'How A Dog Works',
      filename: 'H8U4X...ump',
      timeLeft: '2h 15m',
      percentage: '2.5',
      holders: '4/5',
      rating: 2,
      change: '1.5',
      successRate: 13,
      volume: '80K',
      marketCap: '5K',
      transactions: 14,
      creator: 'Pumpit',
      hasRun: true,
      earnings: 42,
      holdTime: '3d',
    },
    {
      token: 'WOOF47',
      name: 'How A Dog Works',
      filename: 'H8U4X...ump',
      percentage: '2.5',
      holders: '4/5',
      rating: 2,
      change: '1.5',
      successRate: 13,
      volume: '80K',
      marketCap: '5K',
      transactions: 14,
      creator: 'Pumpit',
      hasRun: true,
      earnings: 42,
      holdTime: '3d',
    },
    {
      token: 'WOOF47',
      name: 'How A Dog Works',
      filename: 'H8U4X...ump',
      timeLeft: '2h 15m',
      percentage: '2.5',
      holders: '4/5',
      rating: 2,
      change: '1.5',
      successRate: 13,
      volume: '80K',
      marketCap: '5K',
      transactions: 14,
      creator: 'Pumpit',
      hasRun: true,
      earnings: 42,
      holdTime: '3d',
    },
    {
      token: 'WOOF47',
      name: 'How A Dog Works',
      filename: 'H8U4X...ump',
      percentage: '2.5',
      holders: '4/5',
      rating: 2,
      change: '1.5',
      successRate: 13,
      volume: '80K',
      marketCap: '5K',
      transactions: 14,
      creator: 'Pumpit',
      earnings: 42,
      holdTime: '3d',
    },
    {
      token: 'WOOF47',
      name: 'How A Dog Works',
      filename: 'H8U4X...ump',
      percentage: '2.5',
      holders: '4/5',
      rating: 2,
      change: '1.5',
      successRate: 13,
      volume: '80K',
      marketCap: '5K',
      transactions: 14,
      creator: 'Pumpit',
      hasRun: true,
      earnings: 42,
      holdTime: '3d',
    },
  ],
  completed: [
    {
      token: 'WOOF47',
      name: 'How A Dog Works',
      filename: 'H8U4X...ump',
      percentage: '2.5',
      holders: '4/5',
      rating: 2,
      change: '1.5',
      successRate: 13,
      volume: '80K',
      marketCap: '5K',
      transactions: 14,
      creator: 'Pumpit',
      hasRun: true,
      earnings: 42,
      holdTime: '3d',
    },
    {
      token: 'WOOF47',
      name: 'How A Dog Works',
      filename: 'H8U4X...ump',
      percentage: '2.5',
      holders: '4/5',
      rating: 2,
      change: '1.5',
      successRate: 13,
      volume: '80K',
      marketCap: '5K',
      transactions: 14,
      creator: 'Pumpit',
      hasRun: true,
      earnings: 42,
      holdTime: '3d',
    },
    {
      token: 'WOOF47',
      name: 'How A Dog Works',
      filename: 'H8U4X...ump',
      percentage: '2.5',
      holders: '4/5',
      rating: 2,
      change: '1.5',
      successRate: 13,
      volume: '80K',
      marketCap: '5K',
      transactions: 14,
      creator: 'Pumpit',
      hasRun: true,
      earnings: 42,
      holdTime: '3d',
    },
    {
      token: 'WOOF47',
      name: 'How A Dog Works',
      filename: 'H8U4X...ump',
      percentage: '2.5',
      holders: '4/5',
      rating: 2,
      change: '1.5',
      successRate: 13,
      volume: '80K',
      marketCap: '5K',
      transactions: 14,
      creator: 'Pumpit',
      hasRun: true,
      earnings: 42,
      holdTime: '3d',
    },
    {
      token: 'WOOF47',
      name: 'How A Dog Works',
      filename: 'H8U4X...ump',
      percentage: '2.5',
      holders: '4/5',
      rating: 2,
      change: '1.5',
      successRate: 13,
      volume: '80K',
      marketCap: '5K',
      transactions: 14,
      creator: 'Pumpit',
      hasRun: true,
      earnings: 42,
      holdTime: '3d',
    },
    {
      token: 'WOOF47',
      name: 'How A Dog Works',
      filename: 'H8U4X...ump',
      percentage: '2.5',
      holders: '4/5',
      rating: 2,
      change: '1.5',
      successRate: 13,
      volume: '80K',
      marketCap: '5K',
      transactions: 14,
      creator: 'Pumpit',
      earnings: 42,
      holdTime: '3d',
    },
    {
      token: 'WOOF47',
      name: 'How A Dog Works',
      filename: 'H8U4X...ump',
      percentage: '2.5',
      holders: '4/5',
      rating: 2,
      change: '1.5',
      successRate: 13,
      volume: '80K',
      marketCap: '5K',
      transactions: 14,
      creator: 'Pumpit',
      hasRun: true,
      earnings: 42,
      holdTime: '3d',
    },
  ],
};
